'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,Check,FileText,MessageCircle,MousePointer2,Pause,Play,RotateCcw,Sparkles,Users} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
const screens=['AI tools','Choose subject','Worksheet setup','Worksheet','Assign','Ready'];
const subjects={Mathematics:{topic:'Linear equations',questions:['Solve 3x + 5 = 20. Show each step.','Explain why both sides must stay balanced.','Write an equation for a real situation.']},Science:{topic:'Ecosystems',questions:['Identify a producer in a food chain.','Explain how energy moves through an ecosystem.','Describe what happens if a predator disappears.']}};
export function AIToolsStory(){const [step,setStep]=useState(0),[playing,setPlaying]=useState(true),[hold,setHold]=useState(false),[phase,setPhase]=useState('reading'),[cursor,setCursor]=useState({x:0,y:0}),[subject,setSubject]=useState<keyof typeof subjects>('Mathematics'),[category,setCategory]=useState('Homework'),[audience,setAudience]=useState('Whole class'),[students,setStudents]=useState(['Emma Wilson','Liam Carter']);const ref=useRef<HTMLDivElement>(null);const data=subjects[subject];
const move=()=>{setPlaying(false);setStep(s=>Math.min(5,s+1))};
useEffect(()=>{setPhase('reading');if(!playing||hold)return;let elapsed=0;const timer=setInterval(()=>{const el=ref.current;if(!el||document.hidden||window.matchMedia('(prefers-reduced-motion: reduce)').matches||el.closest('[data-motion=off]'))return;const box=el.getBoundingClientRect();if(!box.width||box.bottom<0||box.top>window.innerHeight)return;const target=el.querySelector<HTMLElement>('[data-auto-action]');if(!target)return;elapsed+=100;const t=target.getBoundingClientRect();setCursor({x:(t.left-box.left+t.width*.6)/(box.width/el.offsetWidth),y:(t.top-box.top+t.height*.6)/(box.width/el.offsetWidth)});if(elapsed>=2900){if(step===1)setSubject('Mathematics');setStep(s=>s===5?0:s+1);return}setPhase(elapsed>=2450?'clicking':elapsed>=1650?'moving':'reading')},100);return()=>clearInterval(timer)},[step,playing,hold]);
return <div className="ap-story ai-story ai-restyled" ref={ref} data-cursor-phase={phase} onMouseEnter={()=>setHold(true)} onMouseLeave={()=>setHold(false)} onFocusCapture={()=>setHold(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHold(false)}}><div className="ps-app-header"><div className="ps-app-brand"><img src="/turito-logo.svg" width={92} height={28} alt="Turito"/><span>Schools</span></div><span className="ps-app-module">AI teaching tools</span></div><div className="ap-progress">{screens.map((name,i)=><button key={name} data-auto-action={step===5&&i===0?true:undefined} aria-label={`Show ${name}`} aria-current={step===i?'step':undefined} onClick={()=>{setStep(i);setPlaying(false)}}><span/>{i===step&&<small>{name}</small>}</button>)}</div><div className="ap-scene" key={step}>
{step===0&&<><div className="ap-heading"><div><small>AI TOOLS / TEACHER WORKSPACE</small><h4>What are you preparing?</h4></div></div><div className="ap-filter"><span>All tools</span><span>Planning</span><span>Teaching</span><span>Writing</span></div><div className="ai-catalog">{[[MessageCircle,'AI Assistant'],[FileText,'Worksheet Generator'],[BookOpen,'Lesson Plan'],[Check,'Rubric Generator'],[Sparkles,'Multiple Explanations'],[FileText,'Writing Feedback']].map(([Icon,name],i)=>{const I=Icon as typeof Sparkles;return i===1?<button key={i} data-auto-action onClick={move}><I size={17}/><strong>{name as string}</strong><ArrowRight size={12}/></button>:<div key={i}><I size={17}/><span>{name as string}</span></div>})}</div></>}
{step===1&&<><div className="ap-heading"><div><small>WORKSHEET GENERATOR</small><h4>Choose a subject.</h4></div></div><div className="ai-subjects">{(Object.keys(subjects) as (keyof typeof subjects)[]).map(s=><button key={s} data-auto-action={s==='Mathematics'?true:undefined} onClick={()=>{setSubject(s);move()}}><BookOpen size={22}/><strong>{s}</strong><ArrowRight size={15}/></button>)}</div><p className="ap-hint">Build practice around what your class is learning.</p></>}
{step===2&&<><div className="ap-heading"><div><small>WORKSHEET GENERATOR / {subject.toUpperCase()}</small><h4>Set the focus.</h4></div></div><div className="ap-fields"><div><small>Subject</small><span>{subject}</span></div><div><small>Class</small><span>Grade 8 · Section A</span></div></div><div className="ai-topic"><small>Topic</small><span>{data.topic}</span></div><div className="ai-question-types"><span>Short answer</span><span>Explain your thinking</span></div><button className="ap-primary" data-auto-action onClick={move}><Sparkles size={13}/> Generate worksheet</button></>}
{step===3&&<><div className="ap-heading"><div><small>GENERATED WORKSHEET</small><h4>{data.topic}</h4></div><span className="ap-badge">Draft</span></div><div className="ai-generated">{data.questions.map((q,i)=><div key={q}><b>{i+1}</b><p>{q}</p></div>)}</div><p className="ap-hint">Review the questions before sharing with students.</p><button className="ap-primary" data-auto-action onClick={move}>Assign worksheet <Users size={13}/></button></>}
{step===4&&<><div className="ap-heading"><div><small>SHARE WITH STUDENTS</small><h4>Put practice within reach.</h4></div></div><RadioGroup aria-label="Assign as" value={category} onValueChange={v=>{setCategory(String(v));setPlaying(false)}} className="ai-share-types">{['Homework','Study material'].map(v=><label key={v}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup><div className="ai-assignment-field"><small>Class</small><span>Grade 8 · Section A</span></div><div className="ai-assignment-field"><small>Assign to</small><Select value={audience} onValueChange={v=>{if(v)setAudience(v);setPlaying(false)}}><SelectTrigger aria-label="Assign to"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Whole class">Whole class</SelectItem><SelectItem value="Selected students">Selected students</SelectItem></SelectContent></Select></div>{audience==='Selected students'&&<div className="ai-students">{['Emma Wilson','Liam Carter','Sofia Martinez'].map(n=><label key={n}><Checkbox checked={students.includes(n)} onCheckedChange={v=>setStudents(s=>v?[...s,n]:s.filter(x=>x!==n))}/>{n}</label>)}</div>}<button className="ap-primary" data-auto-action disabled={audience==='Selected students'&&!students.length} onClick={move}>Assign {category.toLowerCase()} <ArrowRight size={12}/></button></>}
{step===5&&<><div className="ap-heading"><div><small>STUDENT RESOURCES</small><h4>Ready for your learners.</h4></div></div><div className="ai-shared-resource"><FileText size={28}/><strong>{data.topic}</strong><span>{category} · {subject}</span><small>Grade 8 · Section A</small><p><Check size={14}/> {audience==='Whole class'?'Assigned to the whole class':`Assigned to ${students.length} selected students`}</p></div></>}
</div><span className="ap-demo-cursor" aria-hidden="true" style={{left:cursor.x,top:cursor.y}}><MousePointer2 size={22}/><i/></span></div>}
