'use client';
import {ScaledAsset} from './scaled-asset';
import {type CSSProperties} from 'react';

import {ArrowRight,ArrowUpRight,BookOpen,CalendarDays,Check,ChevronRight,ClipboardCheck,FileText,GraduationCap,LayoutGrid,Lightbulb,ListChecks,Mail,Pause,Play,RotateCcw,Sparkles,Users} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
const beats=[
 {label:'Plan the year',title:'Plan the academic year,\nlesson by lesson.',body:'Organize the academic year and connect each lesson to its resources.',module:'Academic Planning',color:'#a4690a',wash:'#fff2bf',icon:CalendarDays,notes:['Shape the yearly plan','Open a unit and its teaching days','Bring resources into the lesson']},
 {label:'Prepare the day',title:'Create teaching materials\nfaster with AI.',body:'Generate teaching materials for your topic, then edit them for your class.',module:'AI Tools',color:'#b84329',wash:'#ffe1d4',icon:Sparkles,notes:['Choose a tool for today’s task','Give it your topic and teaching context','Review the material before class']},
 {label:'Build the test',title:'Build tests with\nquestions and answer keys.',body:'Create curriculum-based tests with flexible question sources and answer keys.',module:'Test Builder',color:'#7252a2',wash:'#eee3fc',icon:ListChecks,notes:['Choose where questions come from','Set question types, difficulty, and marks','Review questions and answers']},
 {label:'Conduct the test',title:'Schedule tests for\nyour classes and students.',body:'Assign tests to your students and manage delivery through completion.',module:'Tests Management',color:'#24765a',wash:'#dcf0df',icon:Users,notes:['Review the assessment before scheduling','Choose students, timing, and delivery','Follow the assessment through completion']},
 {label:'Understand progress',title:'Review student responses\nwith AI-assisted marking.',body:'Review AI-assisted marking and student responses before finalizing results.',module:'AI Evaluations',color:'#a13e5b',wash:'#fbe0e8',icon:ClipboardCheck,notes:['Review rubric-guided marking','Look beyond the total score','Keep teacher judgment in the loop']},
];
const tools=[['Worksheet Generator','Generate topic-based practice',FileText],['Multiple Explanations','Explain a concept in different ways',Lightbulb],['Lesson Plan','Draft lesson objectives and activities',BookOpen],['Rubric Generator','Create assessment criteria',ClipboardCheck],['Email Family','Draft messages to families',Mail],['Presentation Generator','Create lesson slides',LayoutGrid]] as const;
function Badge({children}:{children:React.ReactNode}){return <span className="teach-badge">{children}</span>}
function Plan({detail}:{detail:number}){return <><div className="app-heading"><div><small>ACADEMIC YEAR · 2026–27</small><h3>Yearly Academic Plan</h3></div><Badge>{detail===0?'Draft':'Reviewed'}</Badge></div><div className="plan-summary"><span><b>Grade 8 · Mathematics</b>Year → units → teaching days</span><span>36 weeks</span></div><div className="year-map">{['Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May'].map((m,i)=><span key={m} className={i===2?'month-current':''}>{m}<i style={{background:['#f3ce59','#ed997f','#b5d5b0','#c5afdf'][Math.floor(i/3)]}}/></span>)}</div><div className="unit-grid"><div className="unit-item"><small>UNIT 01</small><b>Number systems</b><span>Foundations & operations</span></div><div className="unit-item unit-selected"><small>UNIT 02 <ArrowRight size={14}/></small><b>Linear equations</b><span>Represent · solve · explain</span></div><div className="unit-item"><small>UNIT 03</small><b>Geometry</b><span>Patterns & relationships</span></div></div><div className={`lesson-detail detail-${detail}`}><div className="detail-heading"><CalendarDays size={16}/><b>Inside the unit</b><span>Week 7</span></div><Table><TableHeader><TableRow><TableHead>Teaching day</TableHead><TableHead>Focus</TableHead><TableHead>Resources</TableHead></TableRow></TableHeader><TableBody>{[['Monday','Keeping equations balanced','Teaching notes'],['Tuesday','Solving two-step equations','Worksheet + AI Plan'],['Wednesday','Explain your reasoning','Practice & feedback']].map((r,i)=><TableRow key={r[0]} className={i===1?'selected-row':''}>{r.map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow>)}</TableBody></Table></div></>}
function Prepare({detail}:{detail:number}){return <><div className="app-heading"><div><small>PLANNING · TEACHING · COMMUNICATION</small><h3>AI Tools</h3></div><Badge>Teacher workspace</Badge></div><div className="ai-workspace"><div className="tool-gallery">{tools.map(([name,desc,Icon],i)=><div className={`tool-item ${i===0?'tool-chosen':''}`} key={name}><Icon size={19}/><b>{name}</b><p>{desc}</p></div>)}</div><div className={`worksheet-sheet detail-${detail}`}><div className="sheet-top"><FileText size={18}/><b>Worksheet Generator</b></div><div className="context-field"><small>TOPIC & CONTEXT</small><p>Grade 8 · Two-step equations<br/>Practice solving and explaining each step.</p></div><div className="worksheet-content"><small>PREVIEW · TEACHER REVIEW</small><h4>Solving two-step equations</h4><p><b>01.</b> Solve 2x + 6 = 14.<br/><span>Explain why you subtract 6 from both sides.</span></p><p><b>02.</b> Write an equation for:<br/><span>Three notebooks and a $2 pen cost $14.</span></p><div className="teacher-note"><Check size={16}/> Review and edit before assigning.</div></div></div></div></>}
function Build({detail}:{detail:number}){return <><div className="app-heading"><div><small>LINEAR EQUATIONS · GRADE 8</small><h3>Test Builder</h3></div><Badge>Practice test</Badge></div><div className="builder-steps">{['Test details','Question setup','Preview questions','Schedule'].map((s,i)=><span className={i===detail?'current':''} key={s}>{i+1} {s}</span>)}</div><div className="question-sources">{['AI Generated','School Question Bank','Turito Question Bank','Manual Upload'].map((s,i)=><div key={s} className={i===1?'source-picked':''}>{i===0?<Sparkles size={18}/>:<FileText size={18}/>}<span>{s}</span>{i===1&&<Check size={14}/>}</div>)}</div><div className="test-composition"><div className="pattern-card"><small>QUESTION PATTERN</small><div><b>Multiple choice</b><span>5 × 2 points</span></div><div><b>Short answer</b><span>5 × 2 points</span></div><p>10 questions · 20 points</p><div className="difficulty"><span>Easy</span><b>Medium</b><span>Hard</span></div></div><div className={`question-preview detail-${detail}`}><small>PREVIEW QUESTIONS · 01</small><h4>Solve: 2x + 6 = 14</h4><div className="question-options">{['x = 2','x = 4','x = 7','x = 10'].map((a,i)=><span key={a} className={i===1?'answer-key':''}>{a}{i===1&&<Check size={14}/>}</span>)}</div><p>Answer key: subtract 6, then divide by 2.</p><div className="teacher-note"><Check size={16}/> Questions checked before assignment</div></div></div></>}
function Conduct({detail}:{detail:number}){return <><div className="app-heading"><div><small>TEST SCHEDULING & DELIVERY</small><h3>Tests Management</h3></div><Badge>{['Draft','Scheduled','Completed'][detail]}</Badge></div><div className="test-summary"><FileText size={29}/><div><h4>Linear equations · Unit check</h4><p>Grade 8A · 10 questions · 20 points</p></div><span className="approval-stamp"><Check size={16}/> Reviewed</span></div><div className="delivery-grid"><div><small>STUDENTS</small><b>Grade 8A</b><p>Selected class & students</p><div className="student-chips"><span>AL</span><span>JS</span><span>MR</span><span>+21</span></div></div><div><small>SCHEDULE</small><b>Oct 16 · 9:15 AM</b><p>30-minute assessment</p><div className="mode-options"><b>Online</b><span>Offline available</span></div></div></div><div className="assessment-track">{['Ready','Assigned','Scheduled','Completed'].map((s,i)=><div className={i<=detail+1?'track-done':''} key={s}><span>{i<=detail+1?<Check size={16}/>:i+1}</span><b>{s}</b></div>)}</div><div className="delivery-note"><CalendarDays size={19}/><p>{detail<2?'Online: timed delivery and student progress monitoring.':'Assessment complete. Responses are ready for review.'}<br/><span>Offline: download a question paper for classroom use.</span></p></div></>}
function Review({detail}:{detail:number}){return <><div className="app-heading"><div><small>LINEAR EQUATIONS · UNIT CHECK</small><h3>Student Evaluation</h3></div><Badge>Pending teacher review</Badge></div><div className="evaluation-flow"><span>Question paper</span><ChevronRight size={13}/><span>Reviewed rubric</span><ChevronRight size={13}/><b>Student responses</b></div><div className="review-grid"><div className="student-results"><small>STUDENT RESULTS</small>{[['Alex L.','16 / 20'],['Jordan S.','14 / 20'],['Morgan R.','18 / 20']].map(([n,v],i)=><div className={i===1?'result-selected':''} key={n}><span>{n}</span><b>{v}</b>{i===1&&<ChevronRight size={15}/>}</div>)}<div className="rubric-note"><ClipboardCheck size={18}/><p>Rubric-guided evaluation<br/><b>Teacher has the final say.</b></p></div></div><div className={`response-detail detail-${detail}`}><small>JORDAN S. · QUESTION 04</small><h4>Explain each step of your solution.</h4><div className="student-answer">2x + 6 = 14<br/>2x = 8<br/>x = 4</div><div className="feedback-pair"><div><Check size={16}/><p><b>Strength</b>Correct calculation</p></div><div><Lightbulb size={16}/><p><b>Practice focus</b>Explain why each step works</p></div></div><div className="review-actions"><span>Override marks</span><b><Check size={15}/> Review & approve</b></div></div></div></>}
export function JourneyHero(){return <section className="ecosystem-hero"><div className="wrap ecosystem-hero-grid"><div><div className="eyebrow">MORE POSSIBILITIES. EVERY SCHOOL DAY.</div><h1>Connected support.<br/><span>Bigger possibilities.</span></h1><p>Empower teachers. Help students build understanding. Connect everyday learning with the opportunities ahead.</p><div className="actions"><a href="/request-demo" className="button">Explore it with us <ArrowUpRight size={19}/></a><a href="#how-it-works" className="text-link">Meet the ecosystem <ArrowRight size={17}/></a></div></div><div className="ecosystem-hero-image"><img src="/learning-together.png" alt="Illustration of a teacher helping students explore a problem together" width={1536} height={1024}/><span className="ecosystem-image-note">A question today.<br/><em>A possibility tomorrow.</em></span></div></div></section>}
const details=[
 'Map units and teaching days, attach materials and homework, and connect topics to the timetable.',
 'Create worksheets, slides, rubrics, alternative explanations, and messages to families.',
 'Use AI, question banks, or uploaded papers; set question types, difficulty, and scoring.',
 'Choose a class or individual students, schedule online or printed tests, and track completion.',
 'Check rubric-based scores, identify learning gaps, and adjust marks where needed.',
];
const photoStories=[
 {image:'/teacher-tools-hero.png',alt:'Teacher preparing lessons at a classroom desk',heading:'Grade 8 · Mathematics',rows:[['Monday','Linear equations'],['Resources','Lesson notes + worksheet']],status:'Academic plan'},
 {image:'/learning-together.png',alt:'Teacher helping students with a lesson',heading:'Worksheet Generator',rows:[['Topic','Two-step equations'],['Materials','Practice + answer key']],status:'Ready to edit'},
 {image:'/academics-hero.png',alt:'Student working with study materials and a notebook',heading:'Linear equations · Unit test',rows:[['Questions','Multiple choice + written'],['Answer key','Solutions and scoring criteria']],status:'Question preview'},
 {image:'/classroom-support.png',alt:'Students working in a classroom with teacher support',heading:'Grade 8 · Unit assessment',rows:[['Schedule','Oct 16 · 9:15 AM'],['Delivery','Online or printed paper']],status:'Scheduled'},
 {image:'/performance-hero.png',alt:'School team reviewing learning reports together',heading:'Response review',rows:[['Calculation','Correct solution'],['Feedback','Explain each operation']],status:'Teacher review'},
];
function TeacherPhotoStory({index}:{index:number}){const c=photoStories[index];const Icon=beats[index].icon;return <figure className="teacher-focused-asset"><div className="photo-detail-brand"><div className="teacher-app-brand"><img src="/turito-logo.svg" alt="Turito" width={80} height={24}/><span>Schools</span></div><span>{beats[index].module}</span></div><div className="focused-asset-heading"><Icon size={23}/><h3>{c.heading}</h3></div>{index===0?<div className="focused-week">{[['Mon','Linear equations'],['Tue','Guided practice'],['Wed','Problem solving']].map(([day,topic])=><div key={day}><small>{day}</small><strong>{topic}</strong><span>Lesson + resources</span></div>)}</div>:index===1?<div className="focused-sheet"><small>WORKSHEET · TWO-STEP EQUATIONS</small><p>1. Solve 2x + 6 = 14.</p><p>2. Explain each step of your solution.</p><span><Check size={14}/> Answer key included</span></div>:index===2?<div className="focused-sheet"><small>QUESTION 1 · MULTIPLE CHOICE</small><p>Solve 2x + 6 = 14.</p><div className="focused-options"><span>x = 2</span><span className="correct">x = 4 <Check size={13}/></span><span>x = 7</span></div><span>Answer: subtract 6, then divide by 2.</span></div>:index===3?<div className="focused-schedule"><CalendarDays size={28}/><div><strong>October 16 · 9:15 AM</strong><span>Grade 8A · 30 minutes</span></div><Check size={18}/></div>:<div className="focused-sheet"><small>WRITTEN RESPONSE · TEACHER REVIEW</small><p>2x + 6 = 14 → 2x = 8 → x = 4</p><span><Check size={14}/> Calculation is correct</span><p className="focused-feedback">Feedback: explain why each operation keeps the equation balanced.</p></div>}<div className="focused-asset-bottom"><span><Check size={13}/>{c.status}</span><span>{index===0?'Materials attached':index===1?'Edit before assigning':index===2?'Question & answer review':index===3?'Online or printed paper':'Adjust marks as needed'}</span></div></figure>}
export function TeacherSolutionSections(){const surfaces=[Plan,Prepare,Build,Conduct,Review];return <div className="teacher-solution-sections" id="teacher-workflow"><div className="wrap solution-sections-intro"><div className="eyebrow">PLANNING, TEACHING & ASSESSMENT</div><h2>Plan lessons. Create materials.<br/><span className="serif">Manage tests and evaluations.</span></h2><p>Explore the tools teachers can use to organize the academic year, prepare class materials, build tests, and review student responses.</p><nav aria-label="Teacher Tools capabilities">{beats.map((b,i)=><a href={`#teacher-capability-${i+1}`} key={b.label}><b>0{i+1}</b>{b.label}<ArrowRight size={15}/></a>)}</nav></div>{beats.map((b,i)=>{const Surface=surfaces[i];return <section className={`teacher-capability capability-${i}`} id={`teacher-capability-${i+1}`} key={b.label} style={{'--beat-color':b.color,'--beat-wash':b.wash} as CSSProperties}><div className="wrap capability-grid"><div className="capability-copy"><span className="capability-label"><b.icon size={21}/>0{i+1} / {b.module}</span><h2>{b.title.split('\n').map(t=><span key={t}>{t}</span>)}</h2><p>{b.body} {details[i]}</p><a href="/request-demo?interest=teacher-tools" className="text-link">See {b.module} in a demo <ArrowUpRight size={17}/></a></div><div className="capability-visual"><ScaledAsset baseWidth={545}><TeacherPhotoStory index={i}/></ScaledAsset></div></div></section>})}</div>}
