'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,CalendarDays,Plus,BookOpen,MousePointer2,Paperclip,Sparkles,FileText} from 'lucide-react';
const names=['Lesson plans','Basic details','Topics & planning','Lesson materials','Calendar'];
export function PlanningStory(){const [step,setStep]=useState(0);const [playing,setPlaying]=useState(true);const [hold,setHold]=useState(false);const ref=useRef<HTMLDivElement>(null);const [materialReady,setMaterialReady]=useState(false);const [phase,setPhase]=useState('reading');const [cursor,setCursor]=useState({x:0,y:0});
useEffect(()=>{
 setPhase('reading');if(!playing||hold)return;
 let elapsed=0;const timer=window.setInterval(()=>{
  const el=ref.current;if(!el||document.hidden||window.matchMedia('(prefers-reduced-motion: reduce)').matches||el.closest('[data-motion=off]'))return;
  const r=el.getBoundingClientRect();if(!r.width||r.bottom<0||r.top>window.innerHeight)return;
  elapsed+=100;
  const generating=step===3&&elapsed<1500;
  if(step===3&&elapsed>=1500)setMaterialReady(true);
  const target=el.querySelector<HTMLElement>(generating?'[data-generate-action]':'[data-auto-action]');if(!target)return;
  const t=target.getBoundingClientRect();const scale=r.width/el.offsetWidth;setCursor({x:(t.left-r.left+t.width*.62)/scale,y:(t.top-r.top+t.height*.6)/scale});
  if(generating){setPhase(elapsed>=1000?'clicking':elapsed>=400?'moving':'reading');return;}
  const progress=step===3?elapsed-1500:elapsed;
  if(progress>=2900){setMaterialReady(false);setStep(s=>s===4?0:s+1);return;}
  setPhase(progress>=2450?'clicking':progress>=1650?'moving':'reading');
 },100);return()=>clearInterval(timer);
},[playing,hold,step]);
const advance=()=>{setPlaying(false);setStep(s=>Math.min(4,s+1))};
return <div className="ps-workflow" data-step={step}><div className="ap-story" data-cursor-phase={phase} ref={ref} onMouseEnter={()=>setHold(true)} onMouseLeave={()=>setHold(false)} onFocusCapture={()=>setHold(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHold(false)}}><div className="ps-app-header"><div className="ps-app-brand"><img src="/turito-logo.svg" width={92} height={28} alt="Turito"/><span>Schools</span></div><span className="ps-app-module">Academic planning</span></div><div className="ap-progress" aria-label={`Planning preview: ${names[step]}`}>{names.map((n,i)=><button key={n} data-auto-action={step===4&&i===0?true:undefined} onClick={()=>{setStep(i);setPlaying(false)}} aria-label={`Show ${n}`} aria-current={i===step?'step':undefined}><span/>{i===step&&<small>{n}</small>}</button>)}</div><div className="ap-scene" key={step}>
{step===0&&<><div className="ap-heading"><div><small>ACADEMIC PLANNING</small><h4>Yearly lesson plans</h4></div><button data-auto-action onClick={advance}><Plus size={12}/> Create plan</button></div><div className="ap-filter"><span>All plans</span><span>Draft</span><span>Scheduled</span></div><table className="ap-table"><thead><tr><th>Subject</th><th>Class</th><th>Weeks</th><th>Status</th></tr></thead><tbody>{[['Mathematics','8 · A','36','Active'],['English','8 · A','36','Draft'],['Science','8 · A','36','Scheduled']].map(row=><tr key={row[0]}>{row.map((v,i)=><td key={i}>{i===3?<span className={`ap-badge ap-${v.toLowerCase().replace(' ','-')}`}>{v}</span>:v}</td>)}</tr>)}</tbody></table><p className="ap-hint">A shared view of subjects, pacing, and plan status.</p></>}
{step===1&&<><div className="ap-heading"><div><small>CREATE NEW LESSON PLAN</small><h4>Start with the year.</h4></div><span className="ap-badge">Draft</span></div><div className="ap-fields">{[['Academic year','2026–2027'],['Subject','Mathematics'],['Class & section','8 · A'],['Duration','36 weeks']].map(([k,v])=><div key={k}><small>{k}</small><span>{v}</span></div>)}</div><div className="ap-note">Set the academic context before mapping topics.</div><button className="ap-primary" data-auto-action onClick={advance}>Add topics <ArrowRight size={12}/></button></>}
{step===2&&<><div className="ap-heading"><div><small>TOPICS & DAILY PLANNING</small><h4>Give each topic a place.</h4></div><CalendarDays size={19}/></div><div className="ap-topic"><strong>Expressions & equations</strong><span>Sep 7–25 · 3 weeks · 12 lessons</span></div><div className="ap-day"><div><span>Tue, Sep 8</span><b>Balancing equations</b></div><dl><dt>Objective</dt><dd>Explain why both sides stay equal</dd><dt>Resources</dt><dd>Lesson notes + worksheet</dd><dt>Homework</dt><dd>Practice set: equations</dd></dl></div><button className="ap-primary" data-auto-action onClick={advance}>Prepare lesson materials <ArrowRight size={12}/></button></>}
{step===3&&<><div className="ap-heading"><div><small>LESSON MATERIALS / BALANCING EQUATIONS</small><h4>Bring the lesson to life.</h4></div></div><div className="ap-material-options"><div><Paperclip size={16}/><strong>Attach your materials</strong><span>Notes, worksheets, and lesson resources</span></div><button type="button" data-generate-action onClick={()=>{setMaterialReady(true);setPlaying(false)}}><Sparkles size={16}/><strong>Create with AI</strong><span>Draft what to teach in this class</span></button></div><div className="ap-attached-file"><FileText size={15}/><span>Equation practice.pdf</span><Check size={13}/></div>{materialReady?<div className="ap-ai-lesson"><span><Sparkles size={14}/> AI LESSON PLAN · DRAFT</span><div><b>Introduce</b><span>Model an equation as a balance.</span></div><div><b>Explore</b><span>Solve together and explain each operation.</span></div><div><b>Check</b><span>Ask students to justify their own solution.</span></div><small>Review and adapt before teaching.</small></div>:<div className="ap-ai-placeholder">Generate a lesson outline to introduce, explore, and check understanding.</div>}<button className="ap-primary" data-auto-action onClick={advance}>Add to lesson <CalendarDays size={12}/></button></>}
{step===4&&<><div className="ap-heading"><div><small>TEACHING CALENDAR</small><h4>The week, across subjects.</h4></div><span className="ap-badge">Sep 7–11</span></div><div className="ap-calendar"><div className="ap-week-labels">{['Mon','Tue','Wed','Thu','Fri'].map(d=><span key={d}>{d}</span>)}</div><div className="ap-week-events">{[['Math','Expressions'],['Math','Equations'],['Science','Ecosystems'],['English','Close reading'],['Math','Practice'],['English','Writing'],['Science','Food webs'],['Math','Word problems'],['Science','Lab notes'],['English','Review']].map(([subject,title],i)=><div className={`ap-event ap-event-${subject.toLowerCase()}`} key={i}><small>{subject}</small><span>{title}</span>{i===1&&<small className="ap-resource-tag"><Paperclip size={9}/> 2 resources</small>}</div>)}</div></div><div className="ap-legend"><span>● Math</span><span>● Science</span><span>● English</span></div><p className="ap-hint">Lesson plans and attached materials, organized across subjects.</p></>}
</div><span className="ap-demo-cursor" aria-hidden="true" style={{left:cursor.x,top:cursor.y}}><MousePointer2 size={22}/><i/></span></div></div>}
