'use client';
import {useEffect,useRef,useState} from 'react';
import {ScaledAsset} from './scaled-asset';
import {StudentModuleStory} from './student-module-story';
import {ArrowRight,ArrowUpRight,BookOpen,ChartNoAxesCombined,Check,FileText,GraduationCap,Layers3,Play,RotateCcw,Sparkles} from 'lucide-react';
import {solutionHref} from './marketing';
const chapters=[
 {id:'learn',label:'Learn',icon:BookOpen,title:'Give students learning resources and AI tutor support.',copy:'Enable access to study materials, lesson recaps, and Virtual AI Tutor explanations so students can revisit classroom topics at their own pace.',link:'academics',cta:'Explore learning support',note:'From the lesson your teacher prepared…'},
 {id:'practice',label:'Practice',icon:Layers3,title:'Build understanding with quizzes and practice.',copy:'Give students practice tests, quizzes, and flashcards to check understanding, learn from mistakes, and reinforce what they study.',link:'academics',cta:'Explore practice & AI tools',note:'…to a chance to try it for yourself.'},
 {id:'reflect',label:'Reflect',icon:ChartNoAxesCombined,title:'Identify strengths and gaps in each subject.',copy:'Connect student engagement with subject-level performance. Help students understand where to focus and teachers plan targeted support.',link:'school-performance',cta:'Explore performance insights',note:'What students do and understand informs the teaching.'},
 {id:'college',label:'Look ahead',icon:GraduationCap,title:'Prepare students for tests and college choices.',copy:'Bring SAT and ACT preparation, student profiles, college recommendations, and Virtual Counselor guidance into your school’s college-readiness support.',link:'college-readiness',cta:'Explore college readiness',note:'A stronger foundation opens more possibilities.'}
];
export function StudentJourney(){const [active,setActive]=useState('learn');const track=useRef<HTMLDivElement>(null);const activeIndex=useRef(0);const changedAt=useRef(0);
useEffect(()=>{let frame=0;let settle:ReturnType<typeof setTimeout>|undefined;const update=()=>{frame=0;const el=track.current;if(!el||document.hidden||window.matchMedia('(max-width:760px), (max-height:700px)').matches)return;const pinned=el.querySelector<HTMLElement>('.sj-tabs');if(!pinned)return;const position=((96-el.getBoundingClientRect().top)/Math.max(1,el.offsetHeight-pinned.offsetHeight))*4;const current=activeIndex.current;let desired=current;if(position>current+1.08)desired=Math.min(3,Math.floor(position));else if(position<current-.08)desired=Math.max(0,Math.floor(position));if(desired===current)return;const remaining=850-(performance.now()-changedAt.current);if(remaining>0){clearTimeout(settle);settle=setTimeout(update,remaining);return;}const index=current+Math.sign(desired-current);activeIndex.current=index;changedAt.current=performance.now();setActive(chapters[index].id);clearTimeout(settle);settle=setTimeout(update,850);};const schedule=()=>{if(!frame)frame=requestAnimationFrame(update)};schedule();window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);return()=>{cancelAnimationFrame(frame);clearTimeout(settle);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule)}},[]);
const select=(value:unknown)=>{const id=String(value);activeIndex.current=chapters.findIndex(c=>c.id===id);changedAt.current=performance.now();setActive(id);const el=track.current;const pinned=el?.querySelector<HTMLElement>('.sj-tabs');if(!el||!pinned||window.matchMedia('(max-width:760px), (max-height:700px)').matches)return;const i=chapters.findIndex(c=>c.id===id);window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-96+(el.offsetHeight-pinned.offsetHeight)*(i+.05)/4,behavior:'auto'})};
return <section className="sj-section" id="student-journey"><div className="wrap"><div className="sj-heading"><div><div className="eyebrow">THE SUPPORT YOUR STUDENTS CAN REACH FOR</div><h2>Support student learning.<br/><em>Build readiness for college.</em></h2></div><p>Equip students with learning resources, guided practice, and college-planning tools. Give school teams insight into where support is needed.</p></div><div className="sj-scroll-track" ref={track}><div className="sj-tabs"><nav className="sj-navigation" aria-label="Student learning journey">{chapters.map(c=><button type="button" key={c.id} onClick={()=>select(c.id)} aria-current={active===c.id?'step':undefined} data-active={active===c.id?'':undefined}><c.icon size={18}/>{c.label}</button>)}</nav>{chapters.map(c=><section key={c.id} className="sj-panel" data-active={active===c.id} aria-labelledby={`student-story-${c.id}-title`}><div className="sj-story-copy"><div className="sj-module-label"><c.icon size={20}/>{c.id==='learn'?'Academics & Virtual AI Tutor':c.id==='practice'?'Practice & AI study tools':c.id==='reflect'?'Student performance':'College readiness'}</div><h3 id={`student-story-${c.id}-title`}>{c.title}</h3><p>{c.copy}</p><a href={solutionHref(c.link)}>{c.cta}<ArrowUpRight size={17}/></a></div><ScaledAsset className="student-scaled-asset"><div className="sj-workspace sj-restyled" data-module={c.id}><div className="ps-app-header"><div className="ps-app-brand"><img src="/turito-logo.svg" width={80} height={24} alt="Turito"/><span>Schools</span></div><span className="ps-app-module">{c.id==='college'?'College readiness':c.id==='reflect'?'My progress':c.id==='practice'?'AI study tools':'Academics & AI Tutor'}</span></div><div className="sj-app-content"><StudentModuleStory module={c.id as 'learn'|'practice'|'reflect'|'college'}/></div></div></ScaledAsset></section>)}</div></div></div></section>}
