'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,ClipboardCheck,FileText,MousePointer2,Pause,Play,Plus,RotateCcw,Sparkles} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
const stages=['Tests','Sources','Question setup','Preview','Schedule','Manage','Results'];
export function TestBuilderStory(){const [step,setStep]=useState(0),[playing,setPlaying]=useState(true),[hold,setHold]=useState(false),[phase,setPhase]=useState('reading'),[cursor,setCursor]=useState({x:0,y:0}),[source,setSource]=useState('School question bank'),[delivery,setDelivery]=useState('Online'),[wholeClass,setWholeClass]=useState(true);const ref=useRef<HTMLDivElement>(null);
const advance=()=>{setPlaying(false);setStep(s=>Math.min(6,s+1))};
useEffect(()=>{setPhase('reading');if(!playing||hold)return;let elapsed=0;const timer=setInterval(()=>{const el=ref.current;if(!el||document.hidden||window.matchMedia('(prefers-reduced-motion: reduce)').matches||el.closest('[data-motion=off]'))return;const box=el.getBoundingClientRect();if(!box.width||box.bottom<0||box.top>window.innerHeight)return;const action=el.querySelector<HTMLElement>('[data-auto-action]');if(!action)return;elapsed+=100;if(step===3){const pane=el.querySelector<HTMLElement>('.tb-preview-scroll');const questions=Array.from(el.querySelectorAll<HTMLElement>('.tb-full-question'));if(pane&&questions.length===3){const start=questions[0].offsetTop;const offsets=questions.map(q=>q.offsetTop-start);let top=0;if(elapsed>1600&&elapsed<2100)top=offsets[1]*(elapsed-1600)/500;else if(elapsed>=2100&&elapsed<3700)top=offsets[1];else if(elapsed>=3700&&elapsed<4200)top=offsets[1]+(offsets[2]-offsets[1])*(elapsed-3700)/500;else if(elapsed>=4200)top=offsets[2];pane.scrollTop=top;}if(elapsed<5800){setPhase('reading');return;}}
const progress=step===3?elapsed-5800:elapsed;const t=action.getBoundingClientRect();setCursor({x:(t.left-box.left+t.width*.6)/(box.width/el.offsetWidth),y:(t.top-box.top+t.height*.6)/(box.width/el.offsetWidth)});if(progress>=2900){setStep(s=>s===6?0:s+1);return}setPhase(progress>=2450?'clicking':progress>=1650?'moving':'reading')},100);return()=>clearInterval(timer)},[step,playing,hold]);
return <div className="ap-story tb-story tb-restyled" ref={ref} data-cursor-phase={phase} onMouseEnter={()=>setHold(true)} onMouseLeave={()=>setHold(false)} onFocusCapture={()=>setHold(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setHold(false)}}><div className="ps-app-header"><div className="ps-app-brand"><img src="/turito-logo.svg" width={92} height={28} alt="Turito"/><span>Schools</span></div><span className="ps-app-module">Test management</span></div><div className="ap-progress">{stages.map((name,i)=><button key={name} data-auto-action={step===6&&i===0?true:undefined} onClick={()=>{setStep(i);setPlaying(false)}} aria-current={i===step?'step':undefined} aria-label={`Show ${name}`}><span/>{step===i&&<small>{name}</small>}</button>)}</div><div className="ap-scene" key={step}>
{step===0&&<><div className="ap-heading"><div><small>TESTS MANAGEMENT</small><h4>Every assessment, in view.</h4></div><button data-auto-action onClick={advance}><Plus size={12}/> Create test</button></div><div className="ap-filter"><span>All tests</span><span>Draft</span><span>Scheduled</span><span>Completed</span></div>{[['Equations · Unit test','Mathematics · Grade 8 · A','Draft'],['Ecosystems · Practice','Science · Grade 8 · A','Scheduled'],['Reading comprehension','English · Grade 8 · A','Completed']].map(([title,meta,status])=><div className="tb-list-row" key={title}><ClipboardCheck size={18}/><div><strong>{title}</strong><small>{meta}</small></div><span className="ap-badge">{status}</span></div>)}</>}
{step===1&&<><div className="ap-heading"><div><small>TEST DETAILS</small><h4>Choose your starting point.</h4></div></div><div className="tb-context"><strong>Equations · Unit test</strong><span>Mathematics · Grade 8 · Section A</span></div><RadioGroup aria-label="Question source" value={source} onValueChange={v=>{setSource(String(v));setPlaying(false)}} className="tb-sources">{['School question bank','Turito question bank','AI-generated','Upload question paper'].map(v=><label key={v}><RadioGroupItem value={v}/><span>{v}</span></label>)}</RadioGroup><button className="ap-primary" data-auto-action onClick={advance}>Set question pattern <ArrowRight size={12}/></button></>}
{step===2&&<><div className="ap-heading"><div><small>QUESTION SETUP</small><h4>Shape what you assess.</h4></div></div><div className="tb-context"><strong>Linear equations</strong><span>Source: {source}</span></div><table className="ap-table"><thead><tr><th>Question type</th><th>Count</th><th>Points each</th></tr></thead><tbody><tr><td>Multiple choice</td><td>4</td><td>1</td></tr><tr><td>Short answer</td><td>2</td><td>2</td></tr><tr><td>Reasoning</td><td>1</td><td>4</td></tr></tbody></table><div className="tb-blueprint"><span>7 questions · 12 points</span><span>Easy / Medium / Hard</span></div><button className="ap-primary" data-auto-action onClick={advance}>Preview questions <ArrowRight size={12}/></button></>}
{step===3&&<><div className="ap-heading"><div><small>TEACHER QUESTION PREVIEW</small><h4>Review questions and answers.</h4></div><span className="ap-badge">3 of 7 shown</span></div><div className="tb-preview-scroll" tabIndex={0} role="region" aria-label="Three questions with answer keys; scroll to review"><article className="tb-full-question"><small>QUESTION 1 · MULTIPLE CHOICE · 1 POINT</small><h5>Solve 3x + 5 = 20.</h5><div className="tb-answer-options"><span>A. x = 3</span><span className="tb-correct">B. x = 5 <Check size={12}/></span><span>C. x = 7</span><span>D. x = 15</span></div><div className="tb-answer-key"><strong>Answer key: B — x = 5</strong><p>Subtract 5 from both sides: 3x = 15. Divide by 3.</p></div></article><article className="tb-full-question"><small>QUESTION 5 · SHORT ANSWER · 2 POINTS</small><h5>A club charges $10 to join and $4 per visit. Write the total cost for 3 visits.</h5><div className="tb-answer-key"><strong>Model answer: $22</strong><p>C = 10 + 4v. For v = 3, C = 10 + 12 = 22.</p></div><div className="tb-marking"><span>1 point · Correct equation</span><span>1 point · Correct substitution and total</span></div></article><article className="tb-full-question"><small>QUESTION 7 · REASONING · 4 POINTS</small><h5>Why must the same operation be applied to both sides of an equation?</h5><div className="tb-answer-key"><strong>Model response</strong><p>The two sides are equal. Applying the same operation to both preserves that equality. For x + 3 = 8, subtracting 3 from both sides gives x = 5.</p></div><div className="tb-marking"><span>2 points · Explain preservation of equality</span><span>2 points · Give a correct worked example</span></div></article></div><small className="tb-scroll-hint">Scroll to review all three question types and marking guidance.</small><button className="ap-primary" data-auto-action onClick={advance}>Schedule & assign <ArrowRight size={12}/></button></>}
{step===4&&<><div className="ap-heading"><div><small>SCHEDULE & ASSIGN</small><h4>Make it part of the week.</h4></div></div><RadioGroup aria-label="Test delivery" value={delivery} onValueChange={v=>{setDelivery(String(v));setPlaying(false)}} className="ai-share-types">{['Online','Paper'].map(v=><label key={v}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup><div className="ap-fields"><div><small>Date & time</small><span>Sep 18 · 10:00 AM</span></div><div><small>Duration</small><span>30 minutes</span></div></div><div className="tb-class"><strong>Grade 8 · Section A</strong><label><Checkbox checked={wholeClass} onCheckedChange={v=>{setWholeClass(Boolean(v));setPlaying(false)}}/> Whole class</label>{!wholeClass&&<span>Selected group · 6 students</span>}</div><button className="ap-primary" data-auto-action onClick={advance}>Schedule test <Check size={12}/></button></>}
{step===5&&<><div className="ap-heading"><div><small>TESTS MANAGEMENT</small><h4>Ready for your class.</h4></div></div><div className="tb-scheduled"><ClipboardCheck size={24}/><strong>Equations · Unit test</strong><span className="ap-badge ap-active">Scheduled</span><p>Sep 18 · 10:00 AM · 30 minutes</p><small>{delivery} · {wholeClass?'Whole class':'6 selected students'} · 7 questions</small></div><div className="tb-time-jump">After students complete the test</div><button className="ap-primary" data-auto-action onClick={advance}>View results <ArrowRight size={12}/></button></>}
{step===6&&<><div className="ap-heading"><div><small>COMPLETED TEST / RESULTS</small><h4>Understand the responses.</h4></div></div><table className="ap-table"><thead><tr><th>Student</th><th>Score</th><th>Status</th></tr></thead><tbody>{[['Emma Wilson','10 / 12'],['Liam Carter','8 / 12'],['Sofia Martinez','9 / 12']].map(([n,score])=><tr key={n}><td>{n}</td><td>{score}</td><td>Completed</td></tr>)}</tbody></table><div className="tb-feedback"><Sparkles size={17}/><div><strong>A focus for follow-up</strong><p>Review written reasoning alongside the scores to identify where support would help.</p></div></div></>}
</div><span className="ap-demo-cursor" aria-hidden="true" style={{left:cursor.x,top:cursor.y}}><MousePointer2 size={22}/><i/></span></div>}
